#You can use the following placeholders in the messages
# (player) - the player who has voted
# (service) - the website that the vote was received from

#message the user is sent when the vote is received.
message_to_user: "&b&lThank you, for voting for us on (service)!"
#message that is sent to the whole server when a person has voted.
broadcast_message: "&l(player) &b&lhas voted for &c&lPicsel&f&lCraft &b&lon (service)&b&l!"


voteCMD:
  titleline: "&b&lVote Sites!"
  votesites:
    votesite1:
      chattext: "&lVote Site 1 - &b&lMinecraft Server List"
      hovertext: "&l&fClick to Open &b&lMinecraft Server List"
      name: "Minecraft Server List"
      url: "https://minecraft-server-list.com/server/465641/vote/"
    votesite2:
      chattext: "&lVote Site 2 - &b&lMinecraftServers"
      hovertext: "&l&fClick to Open &b&lMinecraftServers"
      name: "MinecraftServers"
      url: "https://minecraftservers.org/vote/591943"
    votesite3:
      chattext: "&lVote Site 3 - &b&lMinecraft Multiplayer"
      hovertext: "&l&fClick to Open &b&lMinecraft Multiplayer"
      name: "Minecraft Multiplayer"
      url: "https://minecraft-mp.com/server/265420/vote/"
    votesite4:
      chattext: "&lVote Site 4 - &b&lPlanet Minecraft"
      hovertext: "&l&fClick to Open &b&lPlanet Minecraft"
      name: "Planet Minecraft"
      url: "https://www.planetminecraft.com/server/picselcraft/vote/"



#The command that is run by the plugin to apply the effect of the vote
commands:
  - "lp user (player) permission settemp fawe.permpack.basic true 6h"
  - "pl"

vote_reminder: true
reminder_message: "&9&lDon't forget to vote for us!&b&l See the vote sites by doing /vote !"
reminder_message_hover: "&lClick here to see vote sites!"