name: SimpleVoteListener
main: com.sweepingloutus.simplevotelistener.main
version: 1.0.0
api-version: "1.15"

depend:
  - Votifier
  - PlaceholderAPI

commands:
  vote:
    permission: "svl.list"
  svlreload:
    permission: "svl.reload"